/* eslint-disable max-lines */
import React, { Component } from 'react';
import { StyleSheet, View, Text } from 'react-native';
import PropTypes from 'prop-types';
import { connect } from 'react-redux';

import { withTheme } from '../../contexts/theme';
import SettingsHeaderBackground from '../../components/SettingsHeaderBackground';
import HeaderTitle from '../../components/HeaderTitle';
import Title from '../../components/Title';
import StrongText from '../../components/StrongText';
import Paragraph from '../../components/Paragraph';
import BackButton from '../../components/BackButton';
import DoneButton from '../../components/DoneButton';
import SettingsGroup from '../../components/SettingsGroup';
import BaseSettingsScreen from './BaseSettingsScreen';

const styles = StyleSheet.create({
  view: {
    padding: 20,
    paddingTop: 35
  },
  title: {
    fontSize: 17,
    fontWeight: '600',
    lineHeight: 20,
    letterSpacing: -0.08,
    textAlign: 'left',
    marginTop: 20
  },
  title2: {
    fontSize: 15,
    lineHeight: 17,
    marginTop: 10
  },
  title3: {
    fontSize: 13,
    lineHeight: 15,
    marginTop: 10
  },
  paragraphWrapper: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap'
  },
  paragraph: {
    fontSize: 13,
    lineHeight: 15,
    letterSpacing: -0.08,
    marginBottom: 15
  },
  listItem: {
    marginBottom: 5
  }
});

@connect()
class PrivacyPolicyScreen extends Component {
  static navigationOptions = ({ navigation, screenProps }) => {
    const params = navigation.state.params;
    const isModal = params ? params.isModal : false;
    const headerLeft = isModal ? <Text /> : <BackButton onPress={() => { navigation.goBack(); }} />;
    const headerRight = isModal ? <DoneButton onPress={screenProps.dismiss} /> : null;

    return {
      headerTransparent: true,
      headerBackground: <SettingsHeaderBackground />,
      headerTitle: <HeaderTitle title='Privacy Policy' />,
      headerLeft,
      headerRight
    };
  };

  render() {
    const { theme } = this.props;
    const titleStyles = [styles.title, theme.title];
    const paragraphStyles = [styles.paragraph, theme.text];

    return (
      <BaseSettingsScreen>
        <SettingsGroup style={styles.view}>
          <View style={styles.paragraphWrapper}>
            <Paragraph style={paragraphStyles}>
              Effective date: June 7, 2019
            </Paragraph>
            <Paragraph style={paragraphStyles}>
              Blockfirm AB ("us", "we", or "our") operates the Pine mobile application (hereinafter
              referred to as the "Service").
            </Paragraph>
            <Paragraph style={paragraphStyles}>
              This page informs you of our policies regarding the collection, use and disclosure of
              personal data when you use our Service and the choices you have associated with that
              data.
            </Paragraph>
            <Paragraph style={paragraphStyles}>
              We use your data to provide and improve the Service. By using the Service, you agree
              to the collection and use of information in accordance with this policy. Unless
              otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have
              the same meanings as in our Terms and Conditions.
            </Paragraph>
          </View>

          <Title style={titleStyles}>
            Definitions
          </Title>
          <View style={styles.paragraphWrapper}>
            <Paragraph style={paragraphStyles}>
              <StrongText>Service</StrongText> – Service is the Pine mobile application operated by
              Blockfirm AB.
            </Paragraph>
            <Paragraph style={paragraphStyles}>
              <StrongText>Personal Data</StrongText> – Personal Data means data about a living
              individual who can be identified from those data (or from those and other information
              either in our possession or likely to come into our possession).
            </Paragraph>
            <Paragraph style={paragraphStyles}>
              <StrongText>Bitcoin Data</StrongText> – Bitcoin Data means data that is derived from
              your private key such as public keys and public bitcoin addresses.
            </Paragraph>
            <Paragraph style={paragraphStyles}>
              <StrongText>Usage Data</StrongText> – Usage Data is data collected automatically
              either generated by the use of the Service or from the Service infrastructure itself.
            </Paragraph>
            <Paragraph style={paragraphStyles}>
              <StrongText>Data Controller</StrongText> – Data Controller means the natural or legal
              person who (either alone or jointly or in common with other persons) determines the
              purposes for which and the manner in which any personal information are, or are to be,
              processed.
            </Paragraph>
            <Paragraph style={paragraphStyles}>
              For the purpose of this Privacy Policy, we are a Data Controller of your Personal Data.
            </Paragraph>
            <Paragraph style={paragraphStyles}>
              <StrongText>Data Processors (or Service Providers)</StrongText> – Data Processor (or
              Service Provider) means any natural or legal person who processes the data on behalf
              of the Data Controller.
            </Paragraph>
            <Paragraph style={paragraphStyles}>
              <StrongText>Data Subject (or User)</StrongText> – Data Subject is any living
              individual who is using our Service and is the subject of Personal Data.
            </Paragraph>
          </View>

          <Title style={titleStyles}>
            Information Collection and Use
          </Title>
          <View style={styles.paragraphWrapper}>
            <Paragraph style={paragraphStyles}>
              We collect several different types of information for various purposes to provide and
              improve our Service to you.
            </Paragraph>

            <View>
              <Title style={[titleStyles, styles.title2]}>
                Types of Data Collected
              </Title>
              <View style={styles.paragraphWrapper}>
                <Title style={[titleStyles, styles.title3]}>
                  Bitcoin Data
                </Title>
                <Paragraph style={paragraphStyles}>
                  If you use our Bitcoin Node Service (default), you provide us with the following
                  data:
                </Paragraph>
                <Paragraph style={[paragraphStyles, styles.listItem]}>
                  • Your bitcoin addresses – We use these in order to detect incoming transactions
                  and to update transaction statuses
                </Paragraph>
                <View style={{ marginTop: 10 }}>
                  <Paragraph style={paragraphStyles}>
                    You can choose to not provide us with this data by hosting and using your own
                    bitcoin node.
                  </Paragraph>
                </View>
              </View>

              <View style={styles.paragraphWrapper}>
                <Paragraph style={paragraphStyles}>
                  If your Pine account is provided by us (default), you provide us with the
                  following data:
                </Paragraph>
                <Paragraph style={[paragraphStyles, styles.listItem]}>
                  • Your extended public key – We use this to generate new bitcoin addresses on your
                  behalf for your trusted contacts
                </Paragraph>
                <Paragraph style={[paragraphStyles, styles.listItem]}>
                  • Your public profile information such as display name, username and profile
                  picture
                </Paragraph>
                <Paragraph style={[paragraphStyles, styles.listItem]}>
                  • Your contacts that you have added to the Service
                </Paragraph>
              </View>

              <View style={styles.paragraphWrapper}>
                <Title style={[titleStyles, styles.title3]}>
                  Usage Data
                </Title>
                <Paragraph style={paragraphStyles}>
                  When you access the Service with a mobile device, we may collect certain
                  information automatically, including, but not limited to, the type of mobile
                  device you use, the IP address of your mobile device, your mobile operating system
                  and unique device identifiers.
                </Paragraph>
                <Paragraph style={paragraphStyles}>
                  The usage data that we collect cannot be used to identity you. The unique device
                  identifiers are used to anonymously send you notifications to your mobile device
                  with your permission.
                </Paragraph>
              </View>
            </View>

            <View>
              <Title style={[titleStyles, styles.title2]}>
                Types of Data Not Collected
              </Title>

              <View style={styles.paragraphWrapper}>
                <Title style={[titleStyles, styles.title3]}>
                  Personal Data
                </Title>
                <Paragraph style={paragraphStyles}>
                  We <StrongText>do not</StrongText> intend to collect any personal information that can be used to identify
                  you ("Personal Data") unless you voluntarily provide it to us. Examples when
                  personally identifiable information may be voluntarily provided include, but is
                  not limited to:
                </Paragraph>
                <Paragraph style={[paragraphStyles, styles.listItem]}>
                  • Personal data, such as your email address, provided to us during a support case
                </Paragraph>
                <Paragraph style={[paragraphStyles, styles.listItem]}>
                  • Your real name used as a Display Name in your public profile
                </Paragraph>
                <Paragraph style={[paragraphStyles, styles.listItem]}>
                  • Other personally identifiable information in your public profile
                </Paragraph>
              </View>

              <View style={styles.paragraphWrapper}>
                <Title style={[titleStyles, styles.title3]}>
                  Private Keys
                </Title>
                <Paragraph style={paragraphStyles}>
                  We <StrongText>never</StrongText> collect your private keys in any form and we do
                  not have access to your funds. We are also not able to recover lost funds or reverse
                  bitcoin transactions. You are solely in control of your own funds stored with the
                  Service.
                </Paragraph>
              </View>

              <View style={styles.paragraphWrapper}>
                <Title style={[titleStyles, styles.title3]}>
                  Tracking & Cookies Data
                </Title>
                <Paragraph style={paragraphStyles}>
                  We <StrongText>do not</StrongText> use cookies or similar tracking technologies to
                  track the activity on our Service.
                </Paragraph>
              </View>
            </View>
          </View>

          <Title style={titleStyles}>
            Use of Data
          </Title>
          <View style={styles.paragraphWrapper}>
            <Paragraph style={paragraphStyles}>
              Blockfirm AB uses the collected data for various purposes:
            </Paragraph>
            <Paragraph style={[paragraphStyles, styles.listItem]}>
              • To provide and maintain our Service
            </Paragraph>
            <Paragraph style={[paragraphStyles, styles.listItem]}>
              • To notify you about changes to our Service
            </Paragraph>
            <Paragraph style={[paragraphStyles, styles.listItem]}>
              • To allow you to participate in interactive features of our Service when you choose
              to do so
            </Paragraph>
            <Paragraph style={[paragraphStyles, styles.listItem]}>
              • To provide customer support
            </Paragraph>
            <Paragraph style={[paragraphStyles, styles.listItem]}>
              • To monitor the usage of our Service
            </Paragraph>
            <Paragraph style={[paragraphStyles, styles.listItem]}>
              • To detect, prevent and address technical issues
            </Paragraph>
          </View>

          <Title style={titleStyles}>
            Legal Basis for Processing Personal Data under the General Data Protection Regulation (GDPR)
          </Title>
          <View style={styles.paragraphWrapper}>
            <Paragraph style={paragraphStyles}>
              If you are from the European Economic Area (EEA), Blockfirm AB legal basis for
              collecting and using the personal information described in this Privacy Policy
              depends on the Personal Data we collect and the specific context in which we
              collect it.
            </Paragraph>
            <Paragraph style={paragraphStyles}>
              Blockfirm AB may process your Personal Data because:
            </Paragraph>
            <Paragraph style={[paragraphStyles, styles.listItem]}>
              • We need to perform a contract with you
            </Paragraph>
            <Paragraph style={[paragraphStyles, styles.listItem]}>
              • You have given us permission to do so
            </Paragraph>
            <Paragraph style={[paragraphStyles, styles.listItem]}>
              • The processing is in our legitimate interests and it is not overridden by your rights
            </Paragraph>
            <Paragraph style={[paragraphStyles, styles.listItem]}>
              • To comply with the law
            </Paragraph>
          </View>

          <Title style={titleStyles}>
            Retention of Data
          </Title>
          <View style={styles.paragraphWrapper}>
            <Paragraph style={paragraphStyles}>
              Blockfirm AB will retain your Personal Data only for as long as is necessary for the
              purposes set out in this Privacy Policy.
            </Paragraph>
          </View>

          <Title style={titleStyles}>
            Transfer of Data
          </Title>
          <View style={styles.paragraphWrapper}>
            <Paragraph style={paragraphStyles}>
              Your information, including Personal Data, may be transferred to - and maintained on
              - computers located outside of your state, province, country or other governmental
              jurisdiction where the data protection laws may differ from those of your
              jurisdiction.
            </Paragraph>
            <Paragraph style={paragraphStyles}>
              If you are located outside Sweden and choose to provide information to us, please note
              that we transfer the data, including Personal Data, to Sweden and process it there.
            </Paragraph>
            <Paragraph style={paragraphStyles}>
              Your consent to this Privacy Policy followed by your submission of such information
              represents your agreement to that transfer.
            </Paragraph>
            <Paragraph style={paragraphStyles}>
              Blockfirm AB will take all the steps reasonably necessary to ensure that your data is
              treated securely and in accordance with this Privacy Policy and no transfer of your
              Personal Data will take place to an organisation or a country unless there are adequate
              controls in place including the security of your data and other personal information.
            </Paragraph>
          </View>

          <Title style={titleStyles}>
            Disclosure of Data
          </Title>
          <View style={styles.paragraphWrapper}>
            <View>
              <Title style={[titleStyles, styles.title2]}>
                Business Transaction
              </Title>
              <View style={styles.paragraphWrapper}>
                <Paragraph style={paragraphStyles}>
                  If Blockfirm AB is involved in a merger, acquisition or asset sale, your
                  information, including your Personal Data, may be transferred. We will provide
                  notice before your data is transferred and becomes subject to a different
                  Privacy Policy.
                </Paragraph>
              </View>

              <Title style={[titleStyles, styles.title2]}>
                Legal Requirements
              </Title>
              <View style={styles.paragraphWrapper}>
                <Paragraph style={paragraphStyles}>
                  Blockfirm AB may disclose your Personal Data in the good faith belief that such
                  action is necessary to:
                </Paragraph>
                <Paragraph style={[paragraphStyles, styles.listItem]}>
                  • To comply with a legal obligation
                </Paragraph>
                <Paragraph style={[paragraphStyles, styles.listItem]}>
                  • To protect and defend the rights or property of Blockfirm AB
                </Paragraph>
                <Paragraph style={[paragraphStyles, styles.listItem]}>
                  • To prevent or investigate possible wrongdoing in connection with the Service
                </Paragraph>
                <Paragraph style={[paragraphStyles, styles.listItem]}>
                  • To protect the personal safety of users of the Service or the public
                </Paragraph>
                <Paragraph style={[paragraphStyles, styles.listItem]}>
                  • To protect against legal liability
                </Paragraph>
              </View>
            </View>
          </View>

          <Title style={titleStyles}>
            Security of Data
          </Title>
          <View style={styles.paragraphWrapper}>
            <Paragraph style={paragraphStyles}>
              The security of your data is important to us but remember that no method of
              transmission over the Internet or method of electronic storage is 100% secure. While
              we strive to use commercially acceptable means to protect your data, we
              cannot guarantee its absolute security.
            </Paragraph>
          </View>

          <Title style={titleStyles}>
            Your Data Protection Rights under the General Data Protection Regulation (GDPR)
          </Title>
          <View style={styles.paragraphWrapper}>
            <Paragraph style={paragraphStyles}>
              If you are a resident of the European Economic Area (EEA), you have certain data
              protection rights. Blockfirm AB aims to take reasonable steps to allow you to correct,
              amend, delete or limit the use of your Personal Data.
            </Paragraph>
            <Paragraph style={paragraphStyles}>
              If you wish to be informed about what Personal Data we hold about you and if you want
              it to be removed from our systems, please contact us.
            </Paragraph>
            <Paragraph style={paragraphStyles}>
              In certain circumstances, you have the following data protection rights:
            </Paragraph>
            <Paragraph style={[paragraphStyles, styles.listItem]}>
              • <StrongText>The right to access, update or delete the information we have on you.</StrongText>
              <Text> Whenever made possible, you can access, update or request deletion of your Personal
              Data directly within your account settings section. If you are unable to perform these
              actions yourself, please contact us to assist you.</Text>
            </Paragraph>
            <Paragraph style={[paragraphStyles, styles.listItem]}>
              • <StrongText>The right of rectification.</StrongText>
              <Text> You have the right to have your information rectified if that information is
              inaccurate or incomplete.</Text>
            </Paragraph>
            <Paragraph style={[paragraphStyles, styles.listItem]}>
              • <StrongText>The right to object.</StrongText>
              <Text> You have the right to object to our processing of your Personal Data.</Text>
            </Paragraph>
            <Paragraph style={[paragraphStyles, styles.listItem]}>
              • <StrongText>The right of restriction.</StrongText>
              <Text> You have the right to request that we restrict the processing of your personal
              information.</Text>
            </Paragraph>
            <Paragraph style={[paragraphStyles, styles.listItem]}>
              • <StrongText>The right to data portability.</StrongText>
              <Text> You have the right to be provided with a copy of the information we have on you
              in a structured, machine-readable and commonly used format.</Text>
            </Paragraph>
            <Paragraph style={[paragraphStyles, styles.listItem]}>
              • <StrongText>The right to withdraw consent.</StrongText>
              <Text> You also have the right to withdraw your consent at any time where Blockfirm AB
              relied on your consent to process your personal information.</Text>
            </Paragraph>
            <View style={{ marginTop: 10 }}>
              <Paragraph style={paragraphStyles}>
                Please note that we may ask you to verify your identity before responding to such requests.
              </Paragraph>
              <Paragraph style={paragraphStyles}>
                You have the right to complain to a Data Protection Authority about our collection and
                use of your Personal Data. For more information, please contact your local data
                protection authority in the European Economic Area (EEA).
              </Paragraph>
            </View>
          </View>

          <Title style={titleStyles}>
            Service Providers
          </Title>
          <View style={styles.paragraphWrapper}>
            <Paragraph style={paragraphStyles}>
              We may employ third party companies and individuals to facilitate our Service
              ("Service Providers"), provide the Service on our behalf or perform Service-related
              services.
            </Paragraph>
            <Paragraph style={paragraphStyles}>
              These third parties have access to your data only to perform these tasks on our behalf
              and are obligated not to disclose or use it for any other purpose. Examples include,
              but is not limited to:
            </Paragraph>
            <Paragraph style={[paragraphStyles, styles.listItem]}>
              • Email Service Providers
            </Paragraph>
            <Paragraph style={[paragraphStyles, styles.listItem]}>
              • Cloud Infrastructure Providers
            </Paragraph>
            <View style={{ marginTop: 10 }}>
              <Paragraph style={paragraphStyles}>
                We <StrongText>do not</StrongText> share, sell, rent or trade your data with third
                parties for their commercial purposes.
              </Paragraph>
            </View>
          </View>

          <Title style={titleStyles}>
            Links to Other Sites
          </Title>
          <View style={styles.paragraphWrapper}>
            <Paragraph style={paragraphStyles}>
              Our Service may contain links to other sites that are not operated by us. If you click
              a third party link, you will be directed to that third party's site. We strongly advise
              you to review the Privacy Policy of every site you visit.
            </Paragraph>
            <Paragraph style={paragraphStyles}>
              We have no control over and assume no responsibility for the content, privacy policies
              or practices of any third party sites or services.
            </Paragraph>
          </View>

          <Title style={titleStyles}>
            Changes to This Privacy Policy
          </Title>
          <View style={styles.paragraphWrapper}>
            <Paragraph style={paragraphStyles}>
              We may update our Privacy Policy from time to time. We will notify you of any changes
              by posting the new Privacy Policy on this page.
            </Paragraph>
            <Paragraph style={paragraphStyles}>
              You are advised to review this Privacy Policy periodically for any changes. Changes to
              this Privacy Policy are effective when they are posted on this page.
            </Paragraph>
          </View>

          <Title style={titleStyles}>
            Contact Us
          </Title>
          <View style={styles.paragraphWrapper}>
            <Paragraph style={paragraphStyles}>
              If you have any questions about this Privacy Policy, please contact timothy@blockfirm.se.
            </Paragraph>
          </View>
        </SettingsGroup>
      </BaseSettingsScreen>
    );
  }
}

PrivacyPolicyScreen.propTypes = {
  dispatch: PropTypes.func,
  navigation: PropTypes.any,
  theme: PropTypes.object.isRequired
};

export default withTheme(PrivacyPolicyScreen);
